#!/bin/bash
# ============================================================
#  MTP PROJECT GENERATOR - v1
#  Standard project structure generator + Memory System
#  Works on: Git Bash (Windows), Linux, macOS
#  Usage: ./setup-project.sh
# ============================================================

# Note: Do not use 'set -e' as it breaks piped input (read returns non-zero on EOF)

# Load shared helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/lib/utils.sh" ]; then
  # shellcheck disable=SC1091
  source "$SCRIPT_DIR/lib/utils.sh"
fi

# Load modules
for module in config docker backend frontend docs linting hooks cicd security monitoring environments migrations deployment codegen testing performance dx; do
  if [ -f "$SCRIPT_DIR/lib/$module.sh" ]; then
    # shellcheck disable=SC1091
    source "$SCRIPT_DIR/lib/$module.sh"
  else
    echo "Error: lib/$module.sh not found"
    exit 1
  fi
done

# ============================================================
# HEADER
# ============================================================
cat << "EOF"

  +----------------------------------------------------------+
  |           MTP PROJECT GENERATOR - v1 (Advanced)          |
  |  Standard project structure + Docker + AI Memory System  |
  +----------------------------------------------------------+

EOF

# ============================================================
# INTERACTIVE CONFIGURATION
# ============================================================
prompt_config

# ============================================================
# SUMMARY + CONFIRM
# ============================================================
print_summary

# ============================================================
# CREATE DIRECTORIES
# ============================================================
info "Creating directories"
mkdir -p "$PROJECT_PATH"/{backend,frontend,doc,conversations,.github/workflows,state,scripts}
if [ "$USE_NGINX" = "yes" ]; then
  mkdir -p "$PROJECT_PATH/nginx"
fi
log "Directory structure"

# ============================================================
# GENERATE ALL COMPONENTS
# ============================================================
generate_root_files
generate_nginx
generate_docker_compose

# README.md
if [ "$FRONTEND" = "templ" ]; then
  FRONT_ACCESS="- App (SSR): http://localhost:8080"
else
  FRONT_ACCESS="- Frontend: http://localhost:3000"
fi
cat > "$PROJECT_PATH/README.md" << EOF
# $PROJECT_NAME

Standard structure generated by MTP Project Generator v1

- **Backend:** $BACKEND
- **Frontend:** $FRONTEND ($CSS_FW)
- **Database:** $DB
- **Redis:** $USE_REDIS
- **Nginx:** $USE_NGINX
- **Testing:** $TESTING (backend) / $FRONTEND_TESTING (frontend)

## Quick Start

\`\`\`bash
cp .env.example .env
docker compose up -d --build
\`\`\`

## Access

$FRONT_ACCESS
- Backend: http://localhost:8080
- Health: http://localhost:8080/api/health
- Database: $DB (port: $DB_PORT)
EOF
log "README.md"

# Generate backends and frontends
generate_backend
generate_frontend

# Linting and code quality
generate_linting
generate_hooks
generate_commitlint
generate_editorconfig

# CI/CD
generate_cicd

# Security hardening
generate_security

# Observability (monitoring)
generate_monitoring

# Multi-environment support
generate_environments

# Database migrations
generate_migrations

# Multi-platform deployment
generate_deployment

# Code generation CLI
generate_codegen

# Advanced testing tools
generate_advanced_testing

# Performance optimization
generate_performance

# Developer Experience (DX)
generate_dx

# Documentation and memory system
generate_docs
generate_memory_system

# ============================================================
# INITIALIZE GIT
# ============================================================
if command -v git >/dev/null 2>&1; then
  info "Initializing Git"
  (cd "$PROJECT_PATH" && git init -q && git add -A && git commit -q -m "Initial commit")
  log "Git initialized"
else
  warn "Git not found - skipping initialization"
fi

# ============================================================
# FINAL SUMMARY
# ============================================================
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}  Project created successfully!${NC}"
echo -e "${GREEN}========================================${NC}"
echo -e "\n  ${CYAN}Location:${NC} $PROJECT_PATH"
echo -e "  ${CYAN}Start:${NC}    cd $PROJECT_NAME && docker compose up -d --build"
echo ""
